# Change these first
owner: Xeferis # Your GitHub organization or username, where this repository lives
repo: Website_Status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: No Escape
    url: https://noescape.info

status-website:
  baseUrl: /Website_Status # where "repo" is your repository name
  name: Website Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
