# Change these first
owner: Xeferis # Your GitHub organization or username, where this repository lives
repo: Website_Status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: No Escape
    url: https://noescape.info
    assignees:
      - Xeferis
  - name: Minecraft Server
    check: "tcp-ping"
    url: $MC_IP
    port: 25565
    assignees:
      - Xeferis

status-website:
  theme: night
  # themeUrl: https://xeferis.github.io/Website_Status/custom.css
  baseUrl: /Website_Status # where "repo" is your repository name
  name: Website Status
  navbar:
    - title: Status
      href: /Website_Status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
